add : User 로그인, 회원가입, 데코레이터 View 작성
wecode-bootcamp-korea/14-2nd-MyLittleTrip-backend pull request #3
Opened 2020-12-03 07:36 UTC by BaekChan1024

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인, 회원가입, 로그인 데코레이터 구현 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- test를 먼저 구현하고 view를 구현 하였는 데 순서가 바뀌니 많이 헷갈렸습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-04 05:03 UTC, soheon-lee commented on users/tests.py
> +
tearDown에서 생성해둔 데이터 한 번 지우는 작업을 해주셔야 합니다.
물론 장고는 매 testcase가 끝날 때 디비를 깨끗하게 지워주긴 합니다만, 확인차 tearDown으로 테스트 데이터 다 지워주시는 것이 좋습니다 👍

2020-12-04 05:03 UTC, soheon-lee commented on users/tests.py
> +            'phone_number' : '010-7266-5438'
승찬님 실제 번호인가요? ㅎㅎ

2020-12-04 05:03 UTC, soheon-lee commented on users/tests.py
> +            self.assertEqual(response.json()['message'],'KEY_ERROR')
`json` 은 텍스트 데이터인데 ['message']라는 키를 찾을 수 있던가요??
이 테스트 케이스 정상적으로 작동하나요?

2020-12-04 05:03 UTC, soheon-lee commented on users/tests.py
> +        self.URL = '/users/sigh_up'
오타 모두 수정해주세요~ `Sigh` -> `Sign`

2020-12-04 05:03 UTC, soheon-lee commented on users/tests.py
> +            self.assertEqual(response.status_code,400)
for loop가 첫번째 돌 때에는 `dummy@naver.com`이라는 데이터가 db에 없는 상태이지 않나요? 그렇다면 `OVER_LAP_ERROR`가 뜨지 않고 정상적으로 회원가입이 될 것 같은데, 혹시 제가 로직을 잘못 이해했다면 코멘트로 알려주세요 :-)

2020-12-04 05:03 UTC, soheon-lee commented on users/tests.py
> +    def test_post_success(self):
```suggestion
    def test_sign_up_post_success(self):
```
물론 클래스로 SignUpTest라는 것을 밝혀놓으시긴 하였지만, 테스트 케이스 함수의 이름은 어떤 경우를 테스트하기 위함인지 명확히 알려줄 수 있어야 합니다 :-) 어떤 작업인지 정확하게 알 수 있도록 다른 함수 이름도 모두 좀 더 구체적인 것으로 바꿔주세요~

2020-12-04 05:03 UTC, soheon-lee commented on users/views.py
> +class SighInView(View):
회원가입이 `SignUp`이고, 로그인이 `SignIn` 이어야 하는데, 혹시 View 이름을 잘못 작성하신건 아닌지 확인 부탁드립니다 :)

2020-12-04 05:03 UTC, soheon-lee commented on users/views.py
> +
사용자가 존재하지 않음과 비밀번호가 틀림을 서로 뚜렷하게 구분해서 알려주고 있습니다.
요즘은 보안상의 이유로 두가지 경우를 구분하여 전달하지 않고 있습니다.
두 경우 모두 message를 통일하여 이메일이 틀린건지 비밀번호가 틀린건지 알 수 없도록 해주세요 :) 👍

2020-12-04 05:03 UTC, soheon-lee commented on users/views.py
> +        return JsonResponse({'message' : 'SUCCESS'}, status=200)
테스트 잘 되었고 더이상 사용되지 않는 함수라면 제거해주세요 :)

2020-12-04 05:23 UTC, BaekChan1024 commented on users/tests.py
> +            self.assertEqual(response.json()['message'],'KEY_ERROR')
네 정상적으로 작동하는 거 같습니다

2020-12-04 05:23 UTC, BaekChan1024 commented on users/tests.py
> +            'phone_number' : '010-7266-5438'
네 ㅋㅋㅋㅋ

2020-12-04 05:23 UTC, BaekChan1024 commented on users/tests.py
> +
네 모두 tearDown 적용 하겠습니다.

2020-12-04 05:25 UTC, BaekChan1024 commented on users/tests.py
> +        self.URL = '/users/sigh_up'
수정 하겠습니다.

2020-12-04 05:25 UTC, BaekChan1024 commented on users/tests.py
> +    def test_post_success(self):
다음부터 구체적으로 명시하겠습니다

2020-12-04 05:26 UTC, BaekChan1024 commented on users/views.py
> +class SighInView(View):
view 짤 때 제 정신이 아니었나 봅니다. 수정하겠습니다

2020-12-04 05:27 UTC, BaekChan1024 commented on users/views.py
> +
INVALID_ERROR로 통일 하겠습니다

2020-12-04 07:51 UTC, BaekChan1024 commented on users/tests.py
> +            self.assertEqual(response.status_code,400)
setUp에다가 미리 db에 만들어 두었습니다.

2020-12-07 08:41 UTC, lordmyshepherd requested changes

2020-12-07 08:41 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({'Authorization' : token}, status=200)
# 수정 요청
반환해주는 데이터가 어떤 값인지 정확히 명시해주는 것이 좋을 것 같습니다.
```suggestion
            return JsonResponse({'access_token' : token}, status=200)
```

2020-12-07 09:19 UTC, BaekChan1024 commented on users/views.py
> +            return JsonResponse({'Authorization' : token}, status=200)
넵 수정하겠습니다.

2020-12-08 06:02 UTC, lordmyshepherd requested changes

2020-12-08 06:02 UTC, lordmyshepherd commented on users/views.py
> +class SocialSignInView(View):
Social login unittest를 추가해주세요~

2020-12-08 13:51 UTC, BaekChan1024 commented on users/views.py
> +class SocialSignInView(View):
넵 unit test 추가 하겠습니다!

2020-12-09 07:33 UTC, lordmyshepherd requested changes

2020-12-09 07:33 UTC, lordmyshepherd commented on users/views.py
> +            print(response)
print 문은 지워주세요!

2020-12-09 07:33 UTC, lordmyshepherd commented on users/tests.py
> +        print(response)
프린트만 지워주세요! 완벽합니다!

2020-12-09 07:36 UTC, BaekChan1024 commented on users/views.py
> +            print(response)
디버깅하다가.... 바로 지우겠습니다!

2020-12-09 07:44 UTC, lordmyshepherd commented
LGTM 👍

2020-12-09 07:44 UTC, merged