add : 예약 정보 리스트 뷰 추가
wecode-bootcamp-korea/14-2nd-MyLittleTrip-backend pull request #4
Opened 2020-12-04 05:30 UTC by gyuseok-dev

- 예약 정보 POST 작성
- 예약 정보 리스트 GET 작성
- 테스트 추가
- Serializer 추가

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 항공권 예약내역 리스트 Create 및 Read 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- drf를 적용하기 위해서 settings.py install app 추가
- serializer를 이용하여 다음과 같은 출력이 나오도록 하였습니다. 
![image](https://user-images.githubusercontent.com/69829621/101125707-3b41b900-363d-11eb-9bfa-789a68592701.png)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 현재 예약정보(Reservation)와 티켓정보(Product) 모델이 다대다입니다. 
- 예약정보 post 시 왕복 티켓(2개)와 연결이 필요한데 아직 구현 하지 못했습니다(예약정보 생성만)
- 중간테이블 모델이 없는 상태에서 serializer에서 연결 할 수 있는 방법이 있을까요? 검색은 해봤지만 좋은 답변은 구하지 못했습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-06 03:47 UTC, ulfrid requested changes
확인부탁드립니다.

2020-12-06 03:47 UTC, ulfrid commented on reservations/tests.py
> +        self.product2.reservation_set.add(self.reservation)
tearDown 추가해서 테스트 구간마다 모델 초기화 되도록 해주세요.

2020-12-06 03:47 UTC, ulfrid commented on reservations/views.py
> +        else:
생략할수 있는 else는 제거해주세요. 아래 코드는 한탭 당겨주세요.

2020-12-07 09:08 UTC, lordmyshepherd reviewed
requirements.txt에 rest_framework도 추가해주셨나요?

2020-12-07 11:36 UTC, gyuseok-dev commented
바로 추가하고 APIView로 변경하였습니다.

2020-12-08 05:20 UTC, lordmyshepherd requested changes

2020-12-08 05:20 UTC, lordmyshepherd commented on reservations/views.py
> +class ReservationListView(APIView):
View를 사용하지 않고 APIVeiw를 사용하신 이유가 있으신가요?
handler method 내부 코드가 그대로인 것 같아서 여쭤봅니다.

2020-12-08 05:28 UTC, gyuseok-dev commented on reservations/views.py
> +class ReservationListView(APIView):
네 나중에 drff-yasg를 이용해서 swagget API문서를 만들건데 그때  endpoisnt 가 APIVIew를 사용하해야 문서에 자동으로 추가가 될수 있어 추가하였습니다.

2020-12-08 06:00 UTC, lordmyshepherd commented on reservations/views.py
> +class ReservationListView(APIView):
Django Rest Framwork 공식문서에서 APIView를 찾아보시고, APIView와 View의 차이점을 한번 생각해보세요.

https://www.django-rest-framework.org/api-guide/views/#renderer_classes

APIView를 상속받는다면 handler method 실행 결과로, rest framwork의 Response를 사용하여 값을 리턴해줄 수 있습니다.

JsonResponse를 수정해주세요!

2020-12-09 05:30 UTC, gyuseok-dev commented on reservations/views.py
> +class ReservationListView(APIView):
아 제가 너무 공부가 부족했나 봅니다. APIView를 제대로 활용하지 못하고 있었네요. 수정했습니다. 감사합니다.

2020-12-09 07:43 UTC, lordmyshepherd requested changes

2020-12-09 07:43 UTC, lordmyshepherd commented on reservations/views.py
> +            return Response(serializer.data, status=201)
마지막으로 status code 역시 rest framwork에서 제공하는 status code를 사용해주세요!
힌트) `from rest_framework import status`
```suggestion
            return Response(serializer.data, status=201)
```

2020-12-09 07:43 UTC, lordmyshepherd commented on reservations/tests.py
> +        print(SeatType.objects.all().delete())
print 문이 필요한가요??

2020-12-09 11:01 UTC, lordmyshepherd approved these changes

2020-12-09 11:01 UTC, lordmyshepherd commented
규석님 처음하는 DRF 너무 잘 적용해주셨습니다.
LGTM 👍

2020-12-09 11:01 UTC, merged