add : ProductListview, unit test 완료
wecode-bootcamp-korea/14-2nd-MyLittleTrip-backend pull request #5
Opened 2020-12-04 07:22 UTC by Parkseungje

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
ProductListView 완성및 unit test 완료
		 
## 수정 사항들 자세한 내용
ProductListView 완성및 unit test 완료

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-06 03:53 UTC, ulfrid requested changes
확인 부탁드립니다.

2020-12-06 03:53 UTC, ulfrid commented on products/tests.py
> +        a=Product.objects.create(
a 같은 성의없는 변수명을 지양합시다!

2020-12-06 03:53 UTC, ulfrid commented on products/tests.py
> +           )
setUP 작성을 했다면  tearDown도 해주세요. 테스트 케이스가 증가하면 구간구간 삭제해야. 이후의 테스트에 영향을 주지 않습니다.

2020-12-08 11:15 UTC, Parkseungje commented on products/tests.py
> +        a=Product.objects.create(
수정완료후 다시 올렸습니다.

2020-12-08 11:16 UTC, Parkseungje commented on products/tests.py
> +           )
수정완료후 다시 올렸습니다.

2020-12-10 07:27 UTC, closed without merging