modify : Reservation View post 수정
wecode-bootcamp-korea/14-2nd-MyLittleTrip-backend pull request #8
Opened 2020-12-09 19:11 UTC by gyuseok-dev

- ReservationCreateSerializer 생성
- Reservation 생성시 Product와 연결

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- app url 추가
- reservation create 기능 수정

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- Reservation Row 생성용 serializer 추가
- ReservationCreateSerializer 추가
- PrimayKeyField를 사용하여 product id를 body로 받으면 자동으로 연결
- post 성공 시 테스트 추가, 실제 데이터 페이지에 Product와 연결 여부 검사
- post 시 user 검사 테스트 추가
- post 시 product 검사 테스트 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

이제..잘수있어..

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-10 12:48 UTC, lordmyshepherd requested changes

2020-12-10 12:48 UTC, lordmyshepherd commented on reservations/serializers.py
> +    product = serializers.PrimaryKeyRelatedField(
👍

2020-12-10 12:48 UTC, lordmyshepherd commented on reservations/views.py
> +from .serializers import ReservationSerializer, ReservationCreateSerializer
ReservationSerializer를 사용하지 않는다면, import할 필요가 없을 것 같습니다.
import 문이 실행되면 serializer 객체를 생성해서 ReservationSerializer 이름에 할당해주기 때문에 불필요한 import는 지워주세요.

2020-12-10 12:55 UTC, gyuseok-dev commented on reservations/views.py
> +from .serializers import ReservationSerializer, ReservationCreateSerializer
멘토님 serializer 두개 다 사용합니다. post에서는 ReservationCreateSerializer를 사용하고 get에서는 ReservationSerializer를 사용합니다. 하나는 key 만 필요하고 하나는 nested 로 구현해야되서 나눴습니다. 감사합니다.

2020-12-11 03:48 UTC, lordmyshepherd commented
LGTM 👍

2020-12-11 03:49 UTC, merged